services:
  - type: web
    name: flask-todo-app
    runtime: image
    plan: free
    image:
      url: docker.io/salmaferiel/flask-todo:latest
    envVars:
      - key: POSTGRES_HOST
        fromDatabase:
          name: postgres-db
          property: host
      - key: POSTGRES_USER
        fromDatabase:
          name: postgres-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: postgres-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: postgres-db
          property: database
      - key: REDIS_HOST
        value: ""  # Empty - will use fallback in app code
      - key: REDIS_PORT
        value: "6379"
      - key: PORT
        value: "10000" 

databases:
  - name: postgres-db
    plan: free
    databaseName: tasks
    user: admin