name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t myapp ./app

    - name: Start services
      run: docker compose up -d

    - name: Wait for app to start
      run: sleep 15

    - name: Test API
      run: |
        curl http://localhost/tasks || exit 1